const projects = [
  {
    id: 1,
    title: "Youtube UI",
    url: "#",
    category: "Side",
    imgURL: "/assets/home.jpg",
    description: "HTML+CSS",
    invisible: false,
  },
  {
    id: 2,
    title: "Youtube UI",
    url: "#",
    category: "Side",
    imgURL: "/assets/favicon.png",
    description: "HTML+CSS+JS",
    invisible: false,
  },
  {
    id: 3,
    title: "Youtube UI",
    url: "#",
    category: "Side",
    imgURL: "/assets/profile.jpg",
    description: "REACT",
    invisible: false,
  },
  {
    id: 4,
    title: "Youtube UI",
    url: "#",
    category: "Team",
    imgURL: "/assets/profile.jpg",
    description: "REACT",
    invisible: false,
  },
  {
    id: 5,
    title: "Youtube UI",
    url: "#",
    category: "Team",
    imgURL: "/assets/profile.jpg",
    description: "REACT",
    invisible: false,
  },
  {
    id: 6,
    title: "Youtube UI",
    url: "#",
    category: "Side",
    imgURL: "/assets/favicon.png",
    description: "HTML+CSS+JS",
    invisible: false,
  },
  {
    id: 7,
    title: "Youtube UI",
    url: "#",
    category: "Side",
    imgURL: "/assets/profile.jpg",
    description: "REACT",
    invisible: false,
  },
  {
    id: 8,
    title: "Youtube UI",
    url: "#",
    category: "Team",
    imgURL: "/assets/profile.jpg",
    description: "REACT",
    invisible: false,
  },
];

export default projects;
